services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong!Passw0rd
    ports:
      - '1433:1433'
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MAX_APPEND_SIZE=5242880
    ports:
      - '2113:2113'
      - '1113:1113'